DATA:
    DIR: "/home/rauf/datasets/retechlabs/shelves_detection/harr/gts/"
    VAL_DIR: "/home/rauf/datasets/retechlabs/shelves_detection/harr/gts/"
    TEST_DIR: "/home/rauf/datasets/retechlabs/shelves_detection/harr/gts/"
    SPLIT_FILE: "/home/rauf/datasets/retechlabs/shelves_detection/harr/gts_prepared/folds.csv"
    FOLD: 0
    BATCH_SIZE: 8
    WORKERS: 0

OPTIMIZER:
    OPTIMIZER_TYPE: 'adam'
    LR: 2e-5
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0

    SHEDULER_TYPE: 'cosine'
    T_MAX: 20
    ETA_MIN: 2e-5

MODEL:
    NUMANGLE: 100
    NUMRHO: 100
    THRESHOLD: 0.01
    BACKBONE: resnet50 
    # only support : resnet18, resnet50, resnet101, mobilenetv2, resnext50, res2net50, vgg16

TRAIN:
    EPOCHS: 20
    PRINT_FREQ: 10
    TEST: False
    SEED: 28
    GPU_ID: 0
    DATA_PARALLEL: False
    RESUME: 
    FREEZE_BACKBONE: False
    AUG_TYPE: 'soft'
    LOAD_WEIGHTS: /home/rauf/retechlabs/shelves_detection/deep-hough-transform/work_dirs/harr_resnet50_fold0/model_best.pth

MISC:
    RETAILER: 'harr_new'
    TMP: "./work_dirs/"
